// https://pubs.opengroup.org/onlinepubs/9799919799/basedefs/langinfo.h.html

#include "core.h"

#include <langinfo.h>

TEST(langinfo_h)
{
	TYPE(locale_t);
	TYPE(nl_item);

	MACRO(CODESET);
	MACRO(D_T_FMT)
	MACRO(D_FMT);
	MACRO(T_FMT);
	MACRO(T_FMT_AMPM);
	MACRO(PM_STR);
	MACRO(DAY_1);
	MACRO(DAY_2);
	MACRO(DAY_3);
	MACRO(DAY_4);
	MACRO(DAY_5);
	MACRO(DAY_6);
	MACRO(DAY_7);
	MACRO(ABDAY_1);
	MACRO(ABDAY_2);
	MACRO(ABDAY_3);
	MACRO(ABDAY_4);
	MACRO(ABDAY_5);
	MACRO(ABDAY_6);
	MACRO(ABDAY_7);
	MACRO(MON_1);
	MACRO(MON_2);
	MACRO(MON_3);
	MACRO(MON_4);
	MACRO(MON_5);
	MACRO(MON_6);
	MACRO(MON_7);
	MACRO(MON_8);
	MACRO(MON_9);
	MACRO(MON_10);
	MACRO(MON_11);
	MACRO(MON_12);
	MACRO(ALTMON_1);
	MACRO(ALTMON_2);
	MACRO(ALTMON_3);
	MACRO(ALTMON_4);
	MACRO(ALTMON_5);
	MACRO(ALTMON_6);
	MACRO(ALTMON_7);
	MACRO(ALTMON_8);
	MACRO(ALTMON_9);
	MACRO(ALTMON_1);
	MACRO(ALTMON_11);
	MACRO(ALTMON_12);
	MACRO(ABMON_1);
	MACRO(ABMON_2);
	MACRO(ABMON_3);
	MACRO(ABMON_4);
	MACRO(ABMON_5);
	MACRO(ABMON_6);
	MACRO(ABMON_7);
	MACRO(ABMON_8);
	MACRO(ABMON_9);
	MACRO(ABMON_10);
	MACRO(ABMON_11);
	MACRO(ABMON_12);
	MACRO(ABALTMON_1);
	MACRO(ABALTMON_2);
	MACRO(ABALTMON_3);
	MACRO(ABALTMON_4);
	MACRO(ABALTMON_5);
	MACRO(ABALTMON_6);
	MACRO(ABALTMON_7);
	MACRO(ABALTMON_8);
	MACRO(ABALTMON_9);
	MACRO(ABALTMON_10);
	MACRO(ABALTMON_11);
	MACRO(ABALTMON_12);
	MACRO(ERA);
	MACRO(ERA_D_FMT);
	MACRO(ERA_D_T_FMT);
	MACRO(ERA_T_FMT);
	MACRO(ALT_DIGITS);
	MACRO(RADIXCHAR);
	MACRO(THOUSEP);
	MACRO(YESEXPR);
	MACRO(NOEXPR);
	MACRO(CRNCYSTR);

	FUNCTION(nl_langinfo, FN(char *, nl_item))
	FUNCTION(nl_langinfo_l, FN(char *, nl_item, locale_t))
}
